-- create database test_lco;
-- use test_lco;
-- show databases;
-- select now(); current time
-- create table users(
-- 	name varchar(50),
--     col1 date,
--     col2 time,
--     col3 datetime
-- );
-- desc users;
-- insert into users(name,col1,col2,col3)
-- values('thor','2020-08-14','10:14:22',now()
-- );
-- select * from users;
-- select name, HOUR(col3) from users;
select name, date_format(col3,'%m/%d/%Y') from users;